apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-petclinic
spec:
  selector:
    matchLabels:
      app: app-petclinic
  template:
    metadata:
      labels:
        app: app-petclinic
    spec:
      containers:
      - name: app-petclinic
        image: registry.gitlab.com/khalilismail/petclinic/petclinic_img
        ports:
        - containerPort: 8080
          name: http
